apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hello
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: gcr.io/huda-playground/hello:latest
        name: hello
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: hello-config